// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql/driver"
	"fmt"
	"time"
)

type SignupType string

const (
	SignupTypeEmail  SignupType = "email"
	SignupTypeGoogle SignupType = "google"
	SignupTypeGithub SignupType = "github"
)

func (e *SignupType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SignupType(s)
	case string:
		*e = SignupType(s)
	default:
		return fmt.Errorf("unsupported scan type for SignupType: %T", src)
	}
	return nil
}

type NullSignupType struct {
	SignupType SignupType `json:"signup_type"`
	Valid      bool       `json:"valid"` // Valid is true if SignupType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSignupType) Scan(value interface{}) error {
	if value == nil {
		ns.SignupType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SignupType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSignupType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SignupType), nil
}

type User struct {
	ID           int32      `json:"id"`
	UserName     string     `json:"user_name"`
	HashedPasswd string     `json:"hashed_passwd"`
	SignupType   SignupType `json:"signup_type"`
	CreatedAt    time.Time  `json:"created_at"`
	UpdatedAt    time.Time  `json:"updated_at"`
}
