# Exported from Render on 2026-05-29T03:08:29Z
version: "1"
projects:
- name: My project
  environments:
  - name: Production
    services:
    - type: web
      name: chat-backend
      runtime: docker
      repo: https://github.com/zukigit/chat
      plan: free
      dependsOn:
        - nats
      envVars:
      - key: FRONTEND_URL
        sync: false
      - key: GATEWAY_PUBLIC_URL
        sync: false
      - key: GITHUB_OAUTH_CLIENT_SECRET
        sync: false
      - key: GITHUB_OAUTH_CLIENT_ID
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: CHAT_DB_HOST
        sync: false
      - key: CHAT_DB_PASSWORD
        sync: false
      - key: CHAT_DB_USER
        sync: false
      - key: CHAT_DB_NAME
        sync: false
      - key: NATS_URL
        value: nats://nats:4222
      region: singapore
      dockerContext: .
      dockerfilePath: ./backend/cmd/backend/Dockerfile
      autoDeployTrigger: commit

    - type: pserv
      name: nats
      runtime: image
      image:
        url: docker.io/library/nats:2.12.4-alpine3.22
      plan: free
      startCommand: "-js -sd /data"
      region: singapore