// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/session/session.proto

package session

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetListenPathRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"` // "chat" or "notification"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetListenPathRequest) Reset() {
	*x = GetListenPathRequest{}
	mi := &file_proto_session_session_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetListenPathRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetListenPathRequest) ProtoMessage() {}

func (x *GetListenPathRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_session_session_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetListenPathRequest.ProtoReflect.Descriptor instead.
func (*GetListenPathRequest) Descriptor() ([]byte, []int) {
	return file_proto_session_session_proto_rawDescGZIP(), []int{0}
}

func (x *GetListenPathRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type GetListenPathResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ListenPath    string                 `protobuf:"bytes,1,opt,name=listen_path,json=listenPath,proto3" json:"listen_path,omitempty"`
	ConsumerName  string                 `protobuf:"bytes,2,opt,name=consumer_name,json=consumerName,proto3" json:"consumer_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetListenPathResponse) Reset() {
	*x = GetListenPathResponse{}
	mi := &file_proto_session_session_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetListenPathResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetListenPathResponse) ProtoMessage() {}

func (x *GetListenPathResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_session_session_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetListenPathResponse.ProtoReflect.Descriptor instead.
func (*GetListenPathResponse) Descriptor() ([]byte, []int) {
	return file_proto_session_session_proto_rawDescGZIP(), []int{1}
}

func (x *GetListenPathResponse) GetListenPath() string {
	if x != nil {
		return x.ListenPath
	}
	return ""
}

func (x *GetListenPathResponse) GetConsumerName() string {
	if x != nil {
		return x.ConsumerName
	}
	return ""
}

var File_proto_session_session_proto protoreflect.FileDescriptor

const file_proto_session_session_proto_rawDesc = "" +
	"\n" +
	"\x1bproto/session/session.proto\x12\asession\"*\n" +
	"\x14GetListenPathRequest\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\"]\n" +
	"\x15GetListenPathResponse\x12\x1f\n" +
	"\vlisten_path\x18\x01 \x01(\tR\n" +
	"listenPath\x12#\n" +
	"\rconsumer_name\x18\x02 \x01(\tR\fconsumerName2Y\n" +
	"\aSession\x12N\n" +
	"\rGetListenPath\x12\x1d.session.GetListenPathRequest\x1a\x1e.session.GetListenPathResponseB\x10Z\x0eproto/session/b\x06proto3"

var (
	file_proto_session_session_proto_rawDescOnce sync.Once
	file_proto_session_session_proto_rawDescData []byte
)

func file_proto_session_session_proto_rawDescGZIP() []byte {
	file_proto_session_session_proto_rawDescOnce.Do(func() {
		file_proto_session_session_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_session_session_proto_rawDesc), len(file_proto_session_session_proto_rawDesc)))
	})
	return file_proto_session_session_proto_rawDescData
}

var file_proto_session_session_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_session_session_proto_goTypes = []any{
	(*GetListenPathRequest)(nil),  // 0: session.GetListenPathRequest
	(*GetListenPathResponse)(nil), // 1: session.GetListenPathResponse
}
var file_proto_session_session_proto_depIdxs = []int32{
	0, // 0: session.Session.GetListenPath:input_type -> session.GetListenPathRequest
	1, // 1: session.Session.GetListenPath:output_type -> session.GetListenPathResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_session_session_proto_init() }
func file_proto_session_session_proto_init() {
	if File_proto_session_session_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_session_session_proto_rawDesc), len(file_proto_session_session_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_session_session_proto_goTypes,
		DependencyIndexes: file_proto_session_session_proto_depIdxs,
		MessageInfos:      file_proto_session_session_proto_msgTypes,
	}.Build()
	File_proto_session_session_proto = out.File
	file_proto_session_session_proto_goTypes = nil
	file_proto_session_session_proto_depIdxs = nil
}
