// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.6
// source: proto/friendship/friendship.proto

package friendship

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FriendRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TargetUsername string                 `protobuf:"bytes,1,opt,name=target_username,json=targetUsername,proto3" json:"target_username,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *FriendRequest) Reset() {
	*x = FriendRequest{}
	mi := &file_proto_friendship_friendship_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FriendRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FriendRequest) ProtoMessage() {}

func (x *FriendRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_friendship_friendship_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FriendRequest.ProtoReflect.Descriptor instead.
func (*FriendRequest) Descriptor() ([]byte, []int) {
	return file_proto_friendship_friendship_proto_rawDescGZIP(), []int{0}
}

func (x *FriendRequest) GetTargetUsername() string {
	if x != nil {
		return x.TargetUsername
	}
	return ""
}

type FriendResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FriendResponse) Reset() {
	*x = FriendResponse{}
	mi := &file_proto_friendship_friendship_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FriendResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FriendResponse) ProtoMessage() {}

func (x *FriendResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_friendship_friendship_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FriendResponse.ProtoReflect.Descriptor instead.
func (*FriendResponse) Descriptor() ([]byte, []int) {
	return file_proto_friendship_friendship_proto_rawDescGZIP(), []int{1}
}

func (x *FriendResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_proto_friendship_friendship_proto protoreflect.FileDescriptor

const file_proto_friendship_friendship_proto_rawDesc = "" +
	"\n" +
	"!proto/friendship/friendship.proto\x12\n" +
	"friendship\"8\n" +
	"\rFriendRequest\x12'\n" +
	"\x0ftarget_username\x18\x01 \x01(\tR\x0etargetUsername\"(\n" +
	"\x0eFriendResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status2\xf4\x01\n" +
	"\n" +
	"Friendship\x12J\n" +
	"\x11SendFriendRequest\x12\x19.friendship.FriendRequest\x1a\x1a.friendship.FriendResponse\x12L\n" +
	"\x13AcceptFriendRequest\x12\x19.friendship.FriendRequest\x1a\x1a.friendship.FriendResponse\x12L\n" +
	"\x13RejectFriendRequest\x12\x19.friendship.FriendRequest\x1a\x1a.friendship.FriendResponseB\x13Z\x11proto/friendship/b\x06proto3"

var (
	file_proto_friendship_friendship_proto_rawDescOnce sync.Once
	file_proto_friendship_friendship_proto_rawDescData []byte
)

func file_proto_friendship_friendship_proto_rawDescGZIP() []byte {
	file_proto_friendship_friendship_proto_rawDescOnce.Do(func() {
		file_proto_friendship_friendship_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_friendship_friendship_proto_rawDesc), len(file_proto_friendship_friendship_proto_rawDesc)))
	})
	return file_proto_friendship_friendship_proto_rawDescData
}

var file_proto_friendship_friendship_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_friendship_friendship_proto_goTypes = []any{
	(*FriendRequest)(nil),  // 0: friendship.FriendRequest
	(*FriendResponse)(nil), // 1: friendship.FriendResponse
}
var file_proto_friendship_friendship_proto_depIdxs = []int32{
	0, // 0: friendship.Friendship.SendFriendRequest:input_type -> friendship.FriendRequest
	0, // 1: friendship.Friendship.AcceptFriendRequest:input_type -> friendship.FriendRequest
	0, // 2: friendship.Friendship.RejectFriendRequest:input_type -> friendship.FriendRequest
	1, // 3: friendship.Friendship.SendFriendRequest:output_type -> friendship.FriendResponse
	1, // 4: friendship.Friendship.AcceptFriendRequest:output_type -> friendship.FriendResponse
	1, // 5: friendship.Friendship.RejectFriendRequest:output_type -> friendship.FriendResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_friendship_friendship_proto_init() }
func file_proto_friendship_friendship_proto_init() {
	if File_proto_friendship_friendship_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_friendship_friendship_proto_rawDesc), len(file_proto_friendship_friendship_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_friendship_friendship_proto_goTypes,
		DependencyIndexes: file_proto_friendship_friendship_proto_depIdxs,
		MessageInfos:      file_proto_friendship_friendship_proto_msgTypes,
	}.Build()
	File_proto_friendship_friendship_proto = out.File
	file_proto_friendship_friendship_proto_goTypes = nil
	file_proto_friendship_friendship_proto_depIdxs = nil
}
