// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.0
// source: proto/friendship/friendship.proto

package friendship

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Friendship_SendFriendRequest_FullMethodName   = "/friendship.Friendship/SendFriendRequest"
	Friendship_AcceptFriendRequest_FullMethodName = "/friendship.Friendship/AcceptFriendRequest"
	Friendship_RejectFriendRequest_FullMethodName = "/friendship.Friendship/RejectFriendRequest"
	Friendship_GetFriends_FullMethodName          = "/friendship.Friendship/GetFriends"
)

// FriendshipClient is the client API for Friendship service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FriendshipClient interface {
	SendFriendRequest(ctx context.Context, in *FriendRequest, opts ...grpc.CallOption) (*FriendResponse, error)
	AcceptFriendRequest(ctx context.Context, in *FriendRequest, opts ...grpc.CallOption) (*FriendResponse, error)
	RejectFriendRequest(ctx context.Context, in *FriendRequest, opts ...grpc.CallOption) (*FriendResponse, error)
	GetFriends(ctx context.Context, in *GetFriendsRequest, opts ...grpc.CallOption) (*GetFriendsResponse, error)
}

type friendshipClient struct {
	cc grpc.ClientConnInterface
}

func NewFriendshipClient(cc grpc.ClientConnInterface) FriendshipClient {
	return &friendshipClient{cc}
}

func (c *friendshipClient) SendFriendRequest(ctx context.Context, in *FriendRequest, opts ...grpc.CallOption) (*FriendResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FriendResponse)
	err := c.cc.Invoke(ctx, Friendship_SendFriendRequest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *friendshipClient) AcceptFriendRequest(ctx context.Context, in *FriendRequest, opts ...grpc.CallOption) (*FriendResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FriendResponse)
	err := c.cc.Invoke(ctx, Friendship_AcceptFriendRequest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *friendshipClient) RejectFriendRequest(ctx context.Context, in *FriendRequest, opts ...grpc.CallOption) (*FriendResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FriendResponse)
	err := c.cc.Invoke(ctx, Friendship_RejectFriendRequest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *friendshipClient) GetFriends(ctx context.Context, in *GetFriendsRequest, opts ...grpc.CallOption) (*GetFriendsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetFriendsResponse)
	err := c.cc.Invoke(ctx, Friendship_GetFriends_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FriendshipServer is the server API for Friendship service.
// All implementations must embed UnimplementedFriendshipServer
// for forward compatibility.
type FriendshipServer interface {
	SendFriendRequest(context.Context, *FriendRequest) (*FriendResponse, error)
	AcceptFriendRequest(context.Context, *FriendRequest) (*FriendResponse, error)
	RejectFriendRequest(context.Context, *FriendRequest) (*FriendResponse, error)
	GetFriends(context.Context, *GetFriendsRequest) (*GetFriendsResponse, error)
	mustEmbedUnimplementedFriendshipServer()
}

// UnimplementedFriendshipServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFriendshipServer struct{}

func (UnimplementedFriendshipServer) SendFriendRequest(context.Context, *FriendRequest) (*FriendResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SendFriendRequest not implemented")
}
func (UnimplementedFriendshipServer) AcceptFriendRequest(context.Context, *FriendRequest) (*FriendResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AcceptFriendRequest not implemented")
}
func (UnimplementedFriendshipServer) RejectFriendRequest(context.Context, *FriendRequest) (*FriendResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RejectFriendRequest not implemented")
}
func (UnimplementedFriendshipServer) GetFriends(context.Context, *GetFriendsRequest) (*GetFriendsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetFriends not implemented")
}
func (UnimplementedFriendshipServer) mustEmbedUnimplementedFriendshipServer() {}
func (UnimplementedFriendshipServer) testEmbeddedByValue()                    {}

// UnsafeFriendshipServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FriendshipServer will
// result in compilation errors.
type UnsafeFriendshipServer interface {
	mustEmbedUnimplementedFriendshipServer()
}

func RegisterFriendshipServer(s grpc.ServiceRegistrar, srv FriendshipServer) {
	// If the following call panics, it indicates UnimplementedFriendshipServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Friendship_ServiceDesc, srv)
}

func _Friendship_SendFriendRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FriendRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FriendshipServer).SendFriendRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Friendship_SendFriendRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FriendshipServer).SendFriendRequest(ctx, req.(*FriendRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Friendship_AcceptFriendRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FriendRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FriendshipServer).AcceptFriendRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Friendship_AcceptFriendRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FriendshipServer).AcceptFriendRequest(ctx, req.(*FriendRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Friendship_RejectFriendRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FriendRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FriendshipServer).RejectFriendRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Friendship_RejectFriendRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FriendshipServer).RejectFriendRequest(ctx, req.(*FriendRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Friendship_GetFriends_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFriendsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FriendshipServer).GetFriends(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Friendship_GetFriends_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FriendshipServer).GetFriends(ctx, req.(*GetFriendsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Friendship_ServiceDesc is the grpc.ServiceDesc for Friendship service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Friendship_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "friendship.Friendship",
	HandlerType: (*FriendshipServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendFriendRequest",
			Handler:    _Friendship_SendFriendRequest_Handler,
		},
		{
			MethodName: "AcceptFriendRequest",
			Handler:    _Friendship_AcceptFriendRequest_Handler,
		},
		{
			MethodName: "RejectFriendRequest",
			Handler:    _Friendship_RejectFriendRequest_Handler,
		},
		{
			MethodName: "GetFriends",
			Handler:    _Friendship_GetFriends_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/friendship/friendship.proto",
}
