// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: proto/friendship/friendship.proto

package friendship

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FriendRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TargetUsername string                 `protobuf:"bytes,1,opt,name=target_username,json=targetUsername,proto3" json:"target_username,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *FriendRequest) Reset() {
	*x = FriendRequest{}
	mi := &file_proto_friendship_friendship_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FriendRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FriendRequest) ProtoMessage() {}

func (x *FriendRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_friendship_friendship_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FriendRequest.ProtoReflect.Descriptor instead.
func (*FriendRequest) Descriptor() ([]byte, []int) {
	return file_proto_friendship_friendship_proto_rawDescGZIP(), []int{0}
}

func (x *FriendRequest) GetTargetUsername() string {
	if x != nil {
		return x.TargetUsername
	}
	return ""
}

type FriendResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FriendResponse) Reset() {
	*x = FriendResponse{}
	mi := &file_proto_friendship_friendship_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FriendResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FriendResponse) ProtoMessage() {}

func (x *FriendResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_friendship_friendship_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FriendResponse.ProtoReflect.Descriptor instead.
func (*FriendResponse) Descriptor() ([]byte, []int) {
	return file_proto_friendship_friendship_proto_rawDescGZIP(), []int{1}
}

func (x *FriendResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type GetFriendsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFriendsRequest) Reset() {
	*x = GetFriendsRequest{}
	mi := &file_proto_friendship_friendship_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFriendsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFriendsRequest) ProtoMessage() {}

func (x *GetFriendsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_friendship_friendship_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFriendsRequest.ProtoReflect.Descriptor instead.
func (*GetFriendsRequest) Descriptor() ([]byte, []int) {
	return file_proto_friendship_friendship_proto_rawDescGZIP(), []int{2}
}

type Friend struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	DisplayName   string                 `protobuf:"bytes,3,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	AvatarUrl     string                 `protobuf:"bytes,4,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Friend) Reset() {
	*x = Friend{}
	mi := &file_proto_friendship_friendship_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Friend) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Friend) ProtoMessage() {}

func (x *Friend) ProtoReflect() protoreflect.Message {
	mi := &file_proto_friendship_friendship_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Friend.ProtoReflect.Descriptor instead.
func (*Friend) Descriptor() ([]byte, []int) {
	return file_proto_friendship_friendship_proto_rawDescGZIP(), []int{3}
}

func (x *Friend) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Friend) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *Friend) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *Friend) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

type GetFriendsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Friends       []*Friend              `protobuf:"bytes,1,rep,name=friends,proto3" json:"friends,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFriendsResponse) Reset() {
	*x = GetFriendsResponse{}
	mi := &file_proto_friendship_friendship_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFriendsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFriendsResponse) ProtoMessage() {}

func (x *GetFriendsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_friendship_friendship_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFriendsResponse.ProtoReflect.Descriptor instead.
func (*GetFriendsResponse) Descriptor() ([]byte, []int) {
	return file_proto_friendship_friendship_proto_rawDescGZIP(), []int{4}
}

func (x *GetFriendsResponse) GetFriends() []*Friend {
	if x != nil {
		return x.Friends
	}
	return nil
}

var File_proto_friendship_friendship_proto protoreflect.FileDescriptor

const file_proto_friendship_friendship_proto_rawDesc = "" +
	"\n" +
	"!proto/friendship/friendship.proto\x12\n" +
	"friendship\"8\n" +
	"\rFriendRequest\x12'\n" +
	"\x0ftarget_username\x18\x01 \x01(\tR\x0etargetUsername\"(\n" +
	"\x0eFriendResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\"\x13\n" +
	"\x11GetFriendsRequest\"\x7f\n" +
	"\x06Friend\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12!\n" +
	"\fdisplay_name\x18\x03 \x01(\tR\vdisplayName\x12\x1d\n" +
	"\n" +
	"avatar_url\x18\x04 \x01(\tR\tavatarUrl\"B\n" +
	"\x12GetFriendsResponse\x12,\n" +
	"\afriends\x18\x01 \x03(\v2\x12.friendship.FriendR\afriends2\xc1\x02\n" +
	"\n" +
	"Friendship\x12J\n" +
	"\x11SendFriendRequest\x12\x19.friendship.FriendRequest\x1a\x1a.friendship.FriendResponse\x12L\n" +
	"\x13AcceptFriendRequest\x12\x19.friendship.FriendRequest\x1a\x1a.friendship.FriendResponse\x12L\n" +
	"\x13RejectFriendRequest\x12\x19.friendship.FriendRequest\x1a\x1a.friendship.FriendResponse\x12K\n" +
	"\n" +
	"GetFriends\x12\x1d.friendship.GetFriendsRequest\x1a\x1e.friendship.GetFriendsResponseB\x13Z\x11proto/friendship/b\x06proto3"

var (
	file_proto_friendship_friendship_proto_rawDescOnce sync.Once
	file_proto_friendship_friendship_proto_rawDescData []byte
)

func file_proto_friendship_friendship_proto_rawDescGZIP() []byte {
	file_proto_friendship_friendship_proto_rawDescOnce.Do(func() {
		file_proto_friendship_friendship_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_friendship_friendship_proto_rawDesc), len(file_proto_friendship_friendship_proto_rawDesc)))
	})
	return file_proto_friendship_friendship_proto_rawDescData
}

var file_proto_friendship_friendship_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_friendship_friendship_proto_goTypes = []any{
	(*FriendRequest)(nil),      // 0: friendship.FriendRequest
	(*FriendResponse)(nil),     // 1: friendship.FriendResponse
	(*GetFriendsRequest)(nil),  // 2: friendship.GetFriendsRequest
	(*Friend)(nil),             // 3: friendship.Friend
	(*GetFriendsResponse)(nil), // 4: friendship.GetFriendsResponse
}
var file_proto_friendship_friendship_proto_depIdxs = []int32{
	3, // 0: friendship.GetFriendsResponse.friends:type_name -> friendship.Friend
	0, // 1: friendship.Friendship.SendFriendRequest:input_type -> friendship.FriendRequest
	0, // 2: friendship.Friendship.AcceptFriendRequest:input_type -> friendship.FriendRequest
	0, // 3: friendship.Friendship.RejectFriendRequest:input_type -> friendship.FriendRequest
	2, // 4: friendship.Friendship.GetFriends:input_type -> friendship.GetFriendsRequest
	1, // 5: friendship.Friendship.SendFriendRequest:output_type -> friendship.FriendResponse
	1, // 6: friendship.Friendship.AcceptFriendRequest:output_type -> friendship.FriendResponse
	1, // 7: friendship.Friendship.RejectFriendRequest:output_type -> friendship.FriendResponse
	4, // 8: friendship.Friendship.GetFriends:output_type -> friendship.GetFriendsResponse
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_friendship_friendship_proto_init() }
func file_proto_friendship_friendship_proto_init() {
	if File_proto_friendship_friendship_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_friendship_friendship_proto_rawDesc), len(file_proto_friendship_friendship_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_friendship_friendship_proto_goTypes,
		DependencyIndexes: file_proto_friendship_friendship_proto_depIdxs,
		MessageInfos:      file_proto_friendship_friendship_proto_msgTypes,
	}.Build()
	File_proto_friendship_friendship_proto = out.File
	file_proto_friendship_friendship_proto_goTypes = nil
	file_proto_friendship_friendship_proto_depIdxs = nil
}
