// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: conversation.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const addMemberToConversation = `-- name: AddMemberToConversation :one
INSERT INTO conversation_members (conversation_id, user_id)
VALUES ($1, $2)
RETURNING conversation_id, user_id, joined_at
`

type AddMemberToConversationParams struct {
	ConversationID int64     `json:"conversation_id"`
	UserID         uuid.UUID `json:"user_id"`
}

type AddMemberToConversationRow struct {
	ConversationID int64     `json:"conversation_id"`
	UserID         uuid.UUID `json:"user_id"`
	JoinedAt       time.Time `json:"joined_at"`
}

func (q *Queries) AddMemberToConversation(ctx context.Context, arg AddMemberToConversationParams) (AddMemberToConversationRow, error) {
	row := q.db.QueryRowContext(ctx, addMemberToConversation, arg.ConversationID, arg.UserID)
	var i AddMemberToConversationRow
	err := row.Scan(&i.ConversationID, &i.UserID, &i.JoinedAt)
	return i, err
}

const addMemberWithRole = `-- name: AddMemberWithRole :one
INSERT INTO conversation_members (conversation_id, user_id, role)
VALUES ($1, $2, $3)
RETURNING conversation_id, user_id, joined_at
`

type AddMemberWithRoleParams struct {
	ConversationID int64      `json:"conversation_id"`
	UserID         uuid.UUID  `json:"user_id"`
	Role           MemberRole `json:"role"`
}

type AddMemberWithRoleRow struct {
	ConversationID int64     `json:"conversation_id"`
	UserID         uuid.UUID `json:"user_id"`
	JoinedAt       time.Time `json:"joined_at"`
}

func (q *Queries) AddMemberWithRole(ctx context.Context, arg AddMemberWithRoleParams) (AddMemberWithRoleRow, error) {
	row := q.db.QueryRowContext(ctx, addMemberWithRole, arg.ConversationID, arg.UserID, arg.Role)
	var i AddMemberWithRoleRow
	err := row.Scan(&i.ConversationID, &i.UserID, &i.JoinedAt)
	return i, err
}

const createConversation = `-- name: CreateConversation :one
INSERT INTO conversations (is_group, name)
VALUES ($1, $2)
RETURNING id, is_group, name, created_at, updated_at
`

type CreateConversationParams struct {
	IsGroup bool           `json:"is_group"`
	Name    sql.NullString `json:"name"`
}

func (q *Queries) CreateConversation(ctx context.Context, arg CreateConversationParams) (Conversation, error) {
	row := q.db.QueryRowContext(ctx, createConversation, arg.IsGroup, arg.Name)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.IsGroup,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createDmPeer = `-- name: CreateDmPeer :one
INSERT INTO dm_peers (user1_id, user2_id, conversation_id)
VALUES ($1, $2, $3)
RETURNING user1_id, user2_id, conversation_id
`

type CreateDmPeerParams struct {
	User1ID        uuid.UUID `json:"user1_id"`
	User2ID        uuid.UUID `json:"user2_id"`
	ConversationID int64     `json:"conversation_id"`
}

func (q *Queries) CreateDmPeer(ctx context.Context, arg CreateDmPeerParams) (DmPeer, error) {
	row := q.db.QueryRowContext(ctx, createDmPeer, arg.User1ID, arg.User2ID, arg.ConversationID)
	var i DmPeer
	err := row.Scan(&i.User1ID, &i.User2ID, &i.ConversationID)
	return i, err
}

const getConversation = `-- name: GetConversation :one
SELECT id, is_group, name, created_at, updated_at
FROM conversations
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetConversation(ctx context.Context, id int64) (Conversation, error) {
	row := q.db.QueryRowContext(ctx, getConversation, id)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.IsGroup,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getConversationMembers = `-- name: GetConversationMembers :many
SELECT cm.conversation_id, cm.user_id, cm.joined_at,
       u.user_id, u.user_name, u.display_name, u.avatar_url, u.last_seen_at
FROM conversation_members cm
JOIN users u ON u.user_id = cm.user_id
WHERE cm.conversation_id = $1
`

type GetConversationMembersRow struct {
	ConversationID int64          `json:"conversation_id"`
	UserID         uuid.UUID      `json:"user_id"`
	JoinedAt       time.Time      `json:"joined_at"`
	UserID_2       uuid.UUID      `json:"user_id_2"`
	UserName       string         `json:"user_name"`
	DisplayName    sql.NullString `json:"display_name"`
	AvatarUrl      sql.NullString `json:"avatar_url"`
	LastSeenAt     sql.NullTime   `json:"last_seen_at"`
}

func (q *Queries) GetConversationMembers(ctx context.Context, conversationID int64) ([]GetConversationMembersRow, error) {
	rows, err := q.db.QueryContext(ctx, getConversationMembers, conversationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetConversationMembersRow
	for rows.Next() {
		var i GetConversationMembersRow
		if err := rows.Scan(
			&i.ConversationID,
			&i.UserID,
			&i.JoinedAt,
			&i.UserID_2,
			&i.UserName,
			&i.DisplayName,
			&i.AvatarUrl,
			&i.LastSeenAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getConversationsByUser = `-- name: GetConversationsByUser :many
SELECT c.id, c.is_group, c.name, c.created_at, c.updated_at
FROM conversations c
JOIN conversation_members cm ON cm.conversation_id = c.id
WHERE cm.user_id = $1
ORDER BY c.updated_at DESC
`

// Returns all conversations a user is a member of, most recently updated first.
func (q *Queries) GetConversationsByUser(ctx context.Context, userID uuid.UUID) ([]Conversation, error) {
	rows, err := q.db.QueryContext(ctx, getConversationsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Conversation
	for rows.Next() {
		var i Conversation
		if err := rows.Scan(
			&i.ID,
			&i.IsGroup,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDmPeer = `-- name: GetDmPeer :one
SELECT user1_id, user2_id, conversation_id
FROM dm_peers
WHERE user1_id = $1
  AND user2_id = $2
LIMIT 1
`

type GetDmPeerParams struct {
	User1ID uuid.UUID `json:"user1_id"`
	User2ID uuid.UUID `json:"user2_id"`
}

func (q *Queries) GetDmPeer(ctx context.Context, arg GetDmPeerParams) (DmPeer, error) {
	row := q.db.QueryRowContext(ctx, getDmPeer, arg.User1ID, arg.User2ID)
	var i DmPeer
	err := row.Scan(&i.User1ID, &i.User2ID, &i.ConversationID)
	return i, err
}

const isMember = `-- name: IsMember :one
SELECT EXISTS (
  SELECT 1 FROM conversation_members
  WHERE conversation_id = $1 AND user_id = $2
) AS is_member
`

type IsMemberParams struct {
	ConversationID int64     `json:"conversation_id"`
	UserID         uuid.UUID `json:"user_id"`
}

func (q *Queries) IsMember(ctx context.Context, arg IsMemberParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, isMember, arg.ConversationID, arg.UserID)
	var is_member bool
	err := row.Scan(&is_member)
	return is_member, err
}

const removeMemberFromConversation = `-- name: RemoveMemberFromConversation :exec
DELETE FROM conversation_members
WHERE conversation_id = $1
  AND user_id         = $2
`

type RemoveMemberFromConversationParams struct {
	ConversationID int64     `json:"conversation_id"`
	UserID         uuid.UUID `json:"user_id"`
}

func (q *Queries) RemoveMemberFromConversation(ctx context.Context, arg RemoveMemberFromConversationParams) error {
	_, err := q.db.ExecContext(ctx, removeMemberFromConversation, arg.ConversationID, arg.UserID)
	return err
}
