// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: friendship.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const deleteFriendship = `-- name: DeleteFriendship :exec
DELETE FROM friendships
WHERE user1_userid = $1
  AND user2_userid = $2
`

type DeleteFriendshipParams struct {
	User1Userid uuid.UUID `json:"user1_userid"`
	User2Userid uuid.UUID `json:"user2_userid"`
}

// Deletes the friendship row (used when a request is rejected).
func (q *Queries) DeleteFriendship(ctx context.Context, arg DeleteFriendshipParams) error {
	_, err := q.db.ExecContext(ctx, deleteFriendship, arg.User1Userid, arg.User2Userid)
	return err
}

const getFriends = `-- name: GetFriends :many
SELECT
    CASE
        WHEN f.user1_userid = $1 THEN f.user2_userid
        ELSE f.user1_userid
    END::uuid AS friend_userid,
    u.user_name AS friend_username,
    u.display_name AS friend_display_name,
    u.avatar_url AS friend_avatar_url,
    f.status,
    f.created_at,
    f.updated_at
FROM friendships f
JOIN users u ON u.user_id = (
    CASE
        WHEN f.user1_userid = $1 THEN f.user2_userid
        ELSE f.user1_userid
    END
)
WHERE (f.user1_userid = $1 OR f.user2_userid = $1)
  AND (f.status = 'accepted' OR (f.status = 'pending' AND f.initiator_userid != $1))
`

type GetFriendsRow struct {
	FriendUserid      uuid.UUID        `json:"friend_userid"`
	FriendUsername    string           `json:"friend_username"`
	FriendDisplayName sql.NullString   `json:"friend_display_name"`
	FriendAvatarUrl   sql.NullString   `json:"friend_avatar_url"`
	Status            FriendshipStatus `json:"status"`
	CreatedAt         time.Time        `json:"created_at"`
	UpdatedAt         time.Time        `json:"updated_at"`
}

// Returns all friends (accepted or pending) for a user, including their user_id, username, display_name, avatar_url, and status.
func (q *Queries) GetFriends(ctx context.Context, user1Userid uuid.UUID) ([]GetFriendsRow, error) {
	rows, err := q.db.QueryContext(ctx, getFriends, user1Userid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetFriendsRow
	for rows.Next() {
		var i GetFriendsRow
		if err := rows.Scan(
			&i.FriendUserid,
			&i.FriendUsername,
			&i.FriendDisplayName,
			&i.FriendAvatarUrl,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFriendship = `-- name: GetFriendship :one
SELECT user1_userid, user2_userid, initiator_userid, status, created_at, updated_at
FROM friendships
WHERE user1_userid = $1
  AND user2_userid = $2
LIMIT 1
`

type GetFriendshipParams struct {
	User1Userid uuid.UUID `json:"user1_userid"`
	User2Userid uuid.UUID `json:"user2_userid"`
}

// Always query with the lexicographically smaller UUID as $1.
func (q *Queries) GetFriendship(ctx context.Context, arg GetFriendshipParams) (Friendship, error) {
	row := q.db.QueryRowContext(ctx, getFriendship, arg.User1Userid, arg.User2Userid)
	var i Friendship
	err := row.Scan(
		&i.User1Userid,
		&i.User2Userid,
		&i.InitiatorUserid,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPendingRequests = `-- name: GetPendingRequests :many
SELECT user1_userid, user2_userid, initiator_userid, status, created_at, updated_at
FROM friendships
WHERE user2_userid = $1
  AND status = 'pending'
ORDER BY created_at DESC
`

// Returns incoming friend requests pending for a user.
func (q *Queries) GetPendingRequests(ctx context.Context, user2Userid uuid.UUID) ([]Friendship, error) {
	rows, err := q.db.QueryContext(ctx, getPendingRequests, user2Userid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Friendship
	for rows.Next() {
		var i Friendship
		if err := rows.Scan(
			&i.User1Userid,
			&i.User2Userid,
			&i.InitiatorUserid,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sendFriendRequest = `-- name: SendFriendRequest :one
INSERT INTO friendships (user1_userid, user2_userid, initiator_userid)
VALUES ($1, $2, $3)
RETURNING user1_userid, user2_userid, initiator_userid, status, created_at, updated_at
`

type SendFriendRequestParams struct {
	User1Userid     uuid.UUID `json:"user1_userid"`
	User2Userid     uuid.UUID `json:"user2_userid"`
	InitiatorUserid uuid.UUID `json:"initiator_userid"`
}

// Note: always pass user IDs in lexicographic order (smaller UUID first) to satisfy
// the CHECK (user1_userid < user2_userid) constraint.
// initiator_userid is always the actual caller who triggered the request (before ordering).
func (q *Queries) SendFriendRequest(ctx context.Context, arg SendFriendRequestParams) (Friendship, error) {
	row := q.db.QueryRowContext(ctx, sendFriendRequest, arg.User1Userid, arg.User2Userid, arg.InitiatorUserid)
	var i Friendship
	err := row.Scan(
		&i.User1Userid,
		&i.User2Userid,
		&i.InitiatorUserid,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateFriendshipStatus = `-- name: UpdateFriendshipStatus :one
UPDATE friendships
SET    status     = $3,
       updated_at = NOW()
WHERE  user1_userid = $1
  AND  user2_userid = $2
RETURNING user1_userid, user2_userid, initiator_userid, status, created_at, updated_at
`

type UpdateFriendshipStatusParams struct {
	User1Userid uuid.UUID        `json:"user1_userid"`
	User2Userid uuid.UUID        `json:"user2_userid"`
	Status      FriendshipStatus `json:"status"`
}

func (q *Queries) UpdateFriendshipStatus(ctx context.Context, arg UpdateFriendshipStatusParams) (Friendship, error) {
	row := q.db.QueryRowContext(ctx, updateFriendshipStatus, arg.User1Userid, arg.User2Userid, arg.Status)
	var i Friendship
	err := row.Scan(
		&i.User1Userid,
		&i.User2Userid,
		&i.InitiatorUserid,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
