// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: friendship.sql

package db

import (
	"context"
	"time"
)

const getFriends = `-- name: GetFriends :many
SELECT
    CASE
        WHEN requester_username = $1 THEN addressee_username
        ELSE requester_username
    END AS friend_username,
    status,
    created_at,
    updated_at
FROM friendships
WHERE (requester_username = $1 OR addressee_username = $1)
  AND status = 'accepted'
`

type GetFriendsRow struct {
	FriendUsername interface{}      `json:"friend_username"`
	Status         FriendshipStatus `json:"status"`
	CreatedAt      time.Time        `json:"created_at"`
	UpdatedAt      time.Time        `json:"updated_at"`
}

// Returns all accepted friends for a user.
func (q *Queries) GetFriends(ctx context.Context, requesterUsername string) ([]GetFriendsRow, error) {
	rows, err := q.db.QueryContext(ctx, getFriends, requesterUsername)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetFriendsRow
	for rows.Next() {
		var i GetFriendsRow
		if err := rows.Scan(
			&i.FriendUsername,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFriendship = `-- name: GetFriendship :one
SELECT requester_username, addressee_username, status, created_at, updated_at
FROM friendships
WHERE requester_username = $1
  AND addressee_username = $2
LIMIT 1
`

type GetFriendshipParams struct {
	RequesterUsername string `json:"requester_username"`
	AddresseeUsername string `json:"addressee_username"`
}

// Always query with the lexicographically smaller username as $1.
func (q *Queries) GetFriendship(ctx context.Context, arg GetFriendshipParams) (Friendship, error) {
	row := q.db.QueryRowContext(ctx, getFriendship, arg.RequesterUsername, arg.AddresseeUsername)
	var i Friendship
	err := row.Scan(
		&i.RequesterUsername,
		&i.AddresseeUsername,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPendingRequests = `-- name: GetPendingRequests :many
SELECT requester_username, addressee_username, status, created_at, updated_at
FROM friendships
WHERE addressee_username = $1
  AND status = 'pending'
ORDER BY created_at DESC
`

// Returns incoming friend requests pending for a user.
func (q *Queries) GetPendingRequests(ctx context.Context, addresseeUsername string) ([]Friendship, error) {
	rows, err := q.db.QueryContext(ctx, getPendingRequests, addresseeUsername)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Friendship
	for rows.Next() {
		var i Friendship
		if err := rows.Scan(
			&i.RequesterUsername,
			&i.AddresseeUsername,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sendFriendRequest = `-- name: SendFriendRequest :one
INSERT INTO friendships (requester_username, addressee_username)
VALUES ($1, $2)
RETURNING requester_username, addressee_username, status, created_at, updated_at
`

type SendFriendRequestParams struct {
	RequesterUsername string `json:"requester_username"`
	AddresseeUsername string `json:"addressee_username"`
}

// Note: always pass usernames in lexicographic order (smaller first) to satisfy
// the CHECK (requester_username < addressee_username) constraint.
func (q *Queries) SendFriendRequest(ctx context.Context, arg SendFriendRequestParams) (Friendship, error) {
	row := q.db.QueryRowContext(ctx, sendFriendRequest, arg.RequesterUsername, arg.AddresseeUsername)
	var i Friendship
	err := row.Scan(
		&i.RequesterUsername,
		&i.AddresseeUsername,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateFriendshipStatus = `-- name: UpdateFriendshipStatus :one
UPDATE friendships
SET    status     = $3,
       updated_at = NOW()
WHERE  requester_username = $1
  AND  addressee_username = $2
RETURNING requester_username, addressee_username, status, created_at, updated_at
`

type UpdateFriendshipStatusParams struct {
	RequesterUsername string           `json:"requester_username"`
	AddresseeUsername string           `json:"addressee_username"`
	Status            FriendshipStatus `json:"status"`
}

func (q *Queries) UpdateFriendshipStatus(ctx context.Context, arg UpdateFriendshipStatusParams) (Friendship, error) {
	row := q.db.QueryRowContext(ctx, updateFriendshipStatus, arg.RequesterUsername, arg.AddresseeUsername, arg.Status)
	var i Friendship
	err := row.Scan(
		&i.RequesterUsername,
		&i.AddresseeUsername,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
