// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: messages.sql

package db

import (
	"context"
)

const getConversation = `-- name: GetConversation :many
SELECT id, sender_username, receiver_username, content, is_read, created_at
FROM messages
WHERE
    (sender_username = $1 AND receiver_username = $2)
    OR
    (sender_username = $2 AND receiver_username = $1)
ORDER BY created_at ASC
LIMIT $3 OFFSET $4
`

type GetConversationParams struct {
	SenderUsername   string `json:"sender_username"`
	ReceiverUsername string `json:"receiver_username"`
	Limit            int32  `json:"limit"`
	Offset           int32  `json:"offset"`
}

// Returns messages between two users, oldest first, with pagination.
func (q *Queries) GetConversation(ctx context.Context, arg GetConversationParams) ([]Message, error) {
	rows, err := q.db.QueryContext(ctx, getConversation,
		arg.SenderUsername,
		arg.ReceiverUsername,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Message
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.SenderUsername,
			&i.ReceiverUsername,
			&i.Content,
			&i.IsRead,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getInboxMessages = `-- name: GetInboxMessages :many
SELECT id, sender_username, receiver_username, content, is_read, created_at
FROM messages
WHERE receiver_username = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type GetInboxMessagesParams struct {
	ReceiverUsername string `json:"receiver_username"`
	Limit            int32  `json:"limit"`
	Offset           int32  `json:"offset"`
}

// Returns messages received by a user, newest first, with pagination.
func (q *Queries) GetInboxMessages(ctx context.Context, arg GetInboxMessagesParams) ([]Message, error) {
	rows, err := q.db.QueryContext(ctx, getInboxMessages, arg.ReceiverUsername, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Message
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.SenderUsername,
			&i.ReceiverUsername,
			&i.Content,
			&i.IsRead,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markMessageAsRead = `-- name: MarkMessageAsRead :one
UPDATE messages
SET is_read = TRUE
WHERE id = $1
RETURNING id, sender_username, receiver_username, content, is_read, created_at
`

func (q *Queries) MarkMessageAsRead(ctx context.Context, id int64) (Message, error) {
	row := q.db.QueryRowContext(ctx, markMessageAsRead, id)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.SenderUsername,
		&i.ReceiverUsername,
		&i.Content,
		&i.IsRead,
		&i.CreatedAt,
	)
	return i, err
}

const sendMessage = `-- name: SendMessage :one
INSERT INTO messages (sender_username, receiver_username, content)
VALUES ($1, $2, $3)
RETURNING id, sender_username, receiver_username, content, is_read, created_at
`

type SendMessageParams struct {
	SenderUsername   string `json:"sender_username"`
	ReceiverUsername string `json:"receiver_username"`
	Content          string `json:"content"`
}

func (q *Queries) SendMessage(ctx context.Context, arg SendMessageParams) (Message, error) {
	row := q.db.QueryRowContext(ctx, sendMessage, arg.SenderUsername, arg.ReceiverUsername, arg.Content)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.SenderUsername,
		&i.ReceiverUsername,
		&i.Content,
		&i.IsRead,
		&i.CreatedAt,
	)
	return i, err
}
