// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: messages.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const editMessage = `-- name: EditMessage :one
UPDATE messages
SET content    = $2,
    is_edited  = TRUE,
    updated_at = NOW()
WHERE id = $1
  AND deleted_at IS NULL
RETURNING id, conversation_id, sender_id, content, message_type, media_url, is_edited, deleted_at, created_at, updated_at
`

type EditMessageParams struct {
	ID      int64  `json:"id"`
	Content string `json:"content"`
}

func (q *Queries) EditMessage(ctx context.Context, arg EditMessageParams) (Message, error) {
	row := q.db.QueryRowContext(ctx, editMessage, arg.ID, arg.Content)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.SenderID,
		&i.Content,
		&i.MessageType,
		&i.MediaUrl,
		&i.IsEdited,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getConversationMessages = `-- name: GetConversationMessages :many
SELECT id, conversation_id, sender_id, content, message_type, media_url, is_edited, deleted_at, created_at, updated_at
FROM messages
WHERE conversation_id = $1
  AND deleted_at IS NULL
ORDER BY created_at ASC
LIMIT $2 OFFSET $3
`

type GetConversationMessagesParams struct {
	ConversationID int64 `json:"conversation_id"`
	Limit          int32 `json:"limit"`
	Offset         int32 `json:"offset"`
}

// Returns non-deleted messages in a conversation, oldest first, with pagination.
func (q *Queries) GetConversationMessages(ctx context.Context, arg GetConversationMessagesParams) ([]Message, error) {
	rows, err := q.db.QueryContext(ctx, getConversationMessages, arg.ConversationID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Message
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.SenderID,
			&i.Content,
			&i.MessageType,
			&i.MediaUrl,
			&i.IsEdited,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sendMessage = `-- name: SendMessage :one
INSERT INTO messages (conversation_id, sender_id, content, message_type, media_url)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, conversation_id, sender_id, content, message_type, media_url, is_edited, deleted_at, created_at, updated_at
`

type SendMessageParams struct {
	ConversationID int64          `json:"conversation_id"`
	SenderID       uuid.UUID      `json:"sender_id"`
	Content        string         `json:"content"`
	MessageType    MessageType    `json:"message_type"`
	MediaUrl       sql.NullString `json:"media_url"`
}

func (q *Queries) SendMessage(ctx context.Context, arg SendMessageParams) (Message, error) {
	row := q.db.QueryRowContext(ctx, sendMessage,
		arg.ConversationID,
		arg.SenderID,
		arg.Content,
		arg.MessageType,
		arg.MediaUrl,
	)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.SenderID,
		&i.Content,
		&i.MessageType,
		&i.MediaUrl,
		&i.IsEdited,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const softDeleteMessage = `-- name: SoftDeleteMessage :one
UPDATE messages
SET deleted_at = NOW(),
    updated_at = NOW()
WHERE id = $1
RETURNING id, conversation_id, sender_id, content, message_type, media_url, is_edited, deleted_at, created_at, updated_at
`

func (q *Queries) SoftDeleteMessage(ctx context.Context, id int64) (Message, error) {
	row := q.db.QueryRowContext(ctx, softDeleteMessage, id)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.SenderID,
		&i.Content,
		&i.MessageType,
		&i.MediaUrl,
		&i.IsEdited,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
