// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: message_reads.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const getReadReceiptsForMessage = `-- name: GetReadReceiptsForMessage :many
SELECT mr.user_username, mr.read_at,
       u.display_name, u.avatar_url
FROM message_reads mr
JOIN users u ON u.user_name = mr.user_username
WHERE mr.message_id = $1
`

type GetReadReceiptsForMessageRow struct {
	UserUsername string         `json:"user_username"`
	ReadAt       time.Time      `json:"read_at"`
	DisplayName  sql.NullString `json:"display_name"`
	AvatarUrl    sql.NullString `json:"avatar_url"`
}

// Returns who has read a given message and when.
func (q *Queries) GetReadReceiptsForMessage(ctx context.Context, messageID int64) ([]GetReadReceiptsForMessageRow, error) {
	rows, err := q.db.QueryContext(ctx, getReadReceiptsForMessage, messageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetReadReceiptsForMessageRow
	for rows.Next() {
		var i GetReadReceiptsForMessageRow
		if err := rows.Scan(
			&i.UserUsername,
			&i.ReadAt,
			&i.DisplayName,
			&i.AvatarUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUnreadMessageCount = `-- name: GetUnreadMessageCount :one
SELECT COUNT(*) AS unread_count
FROM messages m
WHERE m.conversation_id = $1
  AND m.sender_username <> $2
  AND m.deleted_at IS NULL
  AND NOT EXISTS (
      SELECT 1 FROM message_reads mr
      WHERE mr.message_id    = m.id
        AND mr.user_username = $2
  )
`

type GetUnreadMessageCountParams struct {
	ConversationID int64  `json:"conversation_id"`
	SenderUsername string `json:"sender_username"`
}

// Counts unread messages in a conversation for a given user.
func (q *Queries) GetUnreadMessageCount(ctx context.Context, arg GetUnreadMessageCountParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, getUnreadMessageCount, arg.ConversationID, arg.SenderUsername)
	var unread_count int64
	err := row.Scan(&unread_count)
	return unread_count, err
}

const markMessageAsRead = `-- name: MarkMessageAsRead :exec
INSERT INTO message_reads (message_id, user_username)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type MarkMessageAsReadParams struct {
	MessageID    int64  `json:"message_id"`
	UserUsername string `json:"user_username"`
}

// Inserts a read receipt; silently ignored if already read (ON CONFLICT DO NOTHING).
func (q *Queries) MarkMessageAsRead(ctx context.Context, arg MarkMessageAsReadParams) error {
	_, err := q.db.ExecContext(ctx, markMessageAsRead, arg.MessageID, arg.UserUsername)
	return err
}
