// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/google/uuid"
)

type FriendshipStatus string

const (
	FriendshipStatusPending  FriendshipStatus = "pending"
	FriendshipStatusAccepted FriendshipStatus = "accepted"
	FriendshipStatusRejected FriendshipStatus = "rejected"
)

func (e *FriendshipStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = FriendshipStatus(s)
	case string:
		*e = FriendshipStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for FriendshipStatus: %T", src)
	}
	return nil
}

type NullFriendshipStatus struct {
	FriendshipStatus FriendshipStatus `json:"friendship_status"`
	Valid            bool             `json:"valid"` // Valid is true if FriendshipStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullFriendshipStatus) Scan(value interface{}) error {
	if value == nil {
		ns.FriendshipStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.FriendshipStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullFriendshipStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.FriendshipStatus), nil
}

type MessageType string

const (
	MessageTypeText  MessageType = "text"
	MessageTypeImage MessageType = "image"
	MessageTypeFile  MessageType = "file"
	MessageTypeAudio MessageType = "audio"
)

func (e *MessageType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MessageType(s)
	case string:
		*e = MessageType(s)
	default:
		return fmt.Errorf("unsupported scan type for MessageType: %T", src)
	}
	return nil
}

type NullMessageType struct {
	MessageType MessageType `json:"message_type"`
	Valid       bool        `json:"valid"` // Valid is true if MessageType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMessageType) Scan(value interface{}) error {
	if value == nil {
		ns.MessageType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MessageType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMessageType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MessageType), nil
}

type NotificationType string

const (
	NotificationTypeMessage       NotificationType = "message"
	NotificationTypeFriendRequest NotificationType = "friend_request"
)

func (e *NotificationType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = NotificationType(s)
	case string:
		*e = NotificationType(s)
	default:
		return fmt.Errorf("unsupported scan type for NotificationType: %T", src)
	}
	return nil
}

type NullNotificationType struct {
	NotificationType NotificationType `json:"notification_type"`
	Valid            bool             `json:"valid"` // Valid is true if NotificationType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullNotificationType) Scan(value interface{}) error {
	if value == nil {
		ns.NotificationType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.NotificationType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullNotificationType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.NotificationType), nil
}

type SignupType string

const (
	SignupTypeEmail  SignupType = "email"
	SignupTypeGoogle SignupType = "google"
	SignupTypeGithub SignupType = "github"
)

func (e *SignupType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SignupType(s)
	case string:
		*e = SignupType(s)
	default:
		return fmt.Errorf("unsupported scan type for SignupType: %T", src)
	}
	return nil
}

type NullSignupType struct {
	SignupType SignupType `json:"signup_type"`
	Valid      bool       `json:"valid"` // Valid is true if SignupType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSignupType) Scan(value interface{}) error {
	if value == nil {
		ns.SignupType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SignupType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSignupType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SignupType), nil
}

type Conversation struct {
	ID        int64          `json:"id"`
	IsGroup   bool           `json:"is_group"`
	Name      sql.NullString `json:"name"`
	CreatedAt time.Time      `json:"created_at"`
	UpdatedAt time.Time      `json:"updated_at"`
}

type ConversationMember struct {
	ConversationID int64     `json:"conversation_id"`
	UserUsername   string    `json:"user_username"`
	JoinedAt       time.Time `json:"joined_at"`
}

type Friendship struct {
	RequesterUsername string           `json:"requester_username"`
	AddresseeUsername string           `json:"addressee_username"`
	Status            FriendshipStatus `json:"status"`
	CreatedAt         time.Time        `json:"created_at"`
	UpdatedAt         time.Time        `json:"updated_at"`
}

type Message struct {
	ID             int64          `json:"id"`
	ConversationID int64          `json:"conversation_id"`
	SenderUsername string         `json:"sender_username"`
	Content        string         `json:"content"`
	MessageType    MessageType    `json:"message_type"`
	MediaUrl       sql.NullString `json:"media_url"`
	IsEdited       bool           `json:"is_edited"`
	DeletedAt      sql.NullTime   `json:"deleted_at"`
	CreatedAt      time.Time      `json:"created_at"`
	UpdatedAt      time.Time      `json:"updated_at"`
}

type MessageRead struct {
	MessageID    int64     `json:"message_id"`
	UserUsername string    `json:"user_username"`
	ReadAt       time.Time `json:"read_at"`
}

type Notification struct {
	ID             int64            `json:"id"`
	UserUsername   string           `json:"user_username"`
	SenderUsername string           `json:"sender_username"`
	Type           NotificationType `json:"type"`
	Message        string           `json:"message"`
	IsRead         bool             `json:"is_read"`
	CreatedAt      time.Time        `json:"created_at"`
}

type User struct {
	UserID       uuid.UUID      `json:"user_id"`
	UserName     string         `json:"user_name"`
	HashedPasswd string         `json:"hashed_passwd"`
	SignupType   SignupType     `json:"signup_type"`
	DisplayName  sql.NullString `json:"display_name"`
	AvatarUrl    sql.NullString `json:"avatar_url"`
	LastSeenAt   sql.NullTime   `json:"last_seen_at"`
	CreatedAt    time.Time      `json:"created_at"`
	UpdatedAt    time.Time      `json:"updated_at"`
}
