// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: notification.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createNotification = `-- name: CreateNotification :one
INSERT INTO notifications (user_id, sender_id, type, message)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, sender_id, type, message, is_read, created_at
`

type CreateNotificationParams struct {
	UserID   uuid.UUID        `json:"user_id"`
	SenderID uuid.UUID        `json:"sender_id"`
	Type     NotificationType `json:"type"`
	Message  string           `json:"message"`
}

func (q *Queries) CreateNotification(ctx context.Context, arg CreateNotificationParams) (Notification, error) {
	row := q.db.QueryRowContext(ctx, createNotification,
		arg.UserID,
		arg.SenderID,
		arg.Type,
		arg.Message,
	)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SenderID,
		&i.Type,
		&i.Message,
		&i.IsRead,
		&i.CreatedAt,
	)
	return i, err
}

const getNotificationsForUser = `-- name: GetNotificationsForUser :many
SELECT id, user_id, sender_id, type, message, is_read, created_at
FROM notifications
WHERE user_id = $1
ORDER BY created_at DESC
`

// Returns all notifications for a user, newest first.
func (q *Queries) GetNotificationsForUser(ctx context.Context, userID uuid.UUID) ([]Notification, error) {
	rows, err := q.db.QueryContext(ctx, getNotificationsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Notification
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.SenderID,
			&i.Type,
			&i.Message,
			&i.IsRead,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUnreadNotificationCount = `-- name: GetUnreadNotificationCount :one
SELECT COUNT(*) AS unread_count
FROM notifications
WHERE user_id = $1
  AND is_read = FALSE
`

func (q *Queries) GetUnreadNotificationCount(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, getUnreadNotificationCount, userID)
	var unread_count int64
	err := row.Scan(&unread_count)
	return unread_count, err
}

const markAllNotificationsAsRead = `-- name: MarkAllNotificationsAsRead :exec
UPDATE notifications
SET is_read = TRUE
WHERE user_id = $1
  AND is_read = FALSE
`

func (q *Queries) MarkAllNotificationsAsRead(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, markAllNotificationsAsRead, userID)
	return err
}

const markNotificationAsRead = `-- name: MarkNotificationAsRead :one
UPDATE notifications
SET is_read = TRUE
WHERE id = $1
RETURNING id, user_id, sender_id, type, message, is_read, created_at
`

func (q *Queries) MarkNotificationAsRead(ctx context.Context, id int64) (Notification, error) {
	row := q.db.QueryRowContext(ctx, markNotificationAsRead, id)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SenderID,
		&i.Type,
		&i.Message,
		&i.IsRead,
		&i.CreatedAt,
	)
	return i, err
}
