// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: notification.sql

package db

import (
	"context"
	"database/sql"
)

const createNotification = `-- name: CreateNotification :one
INSERT INTO notifications (user_username, type, message_id)
VALUES ($1, $2, $3)
RETURNING id, user_username, type, message_id, is_read, created_at
`

type CreateNotificationParams struct {
	UserUsername string           `json:"user_username"`
	Type         NotificationType `json:"type"`
	MessageID    sql.NullInt64    `json:"message_id"`
}

func (q *Queries) CreateNotification(ctx context.Context, arg CreateNotificationParams) (Notification, error) {
	row := q.db.QueryRowContext(ctx, createNotification, arg.UserUsername, arg.Type, arg.MessageID)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.UserUsername,
		&i.Type,
		&i.MessageID,
		&i.IsRead,
		&i.CreatedAt,
	)
	return i, err
}

const getNotificationsForUser = `-- name: GetNotificationsForUser :many
SELECT id, user_username, type, message_id, is_read, created_at
FROM notifications
WHERE user_username = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type GetNotificationsForUserParams struct {
	UserUsername string `json:"user_username"`
	Limit        int32  `json:"limit"`
	Offset       int32  `json:"offset"`
}

// Returns notifications for a user, newest first, with pagination.
func (q *Queries) GetNotificationsForUser(ctx context.Context, arg GetNotificationsForUserParams) ([]Notification, error) {
	rows, err := q.db.QueryContext(ctx, getNotificationsForUser, arg.UserUsername, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Notification
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.UserUsername,
			&i.Type,
			&i.MessageID,
			&i.IsRead,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUnreadNotificationCount = `-- name: GetUnreadNotificationCount :one
SELECT COUNT(*) AS unread_count
FROM notifications
WHERE user_username = $1
  AND is_read = FALSE
`

func (q *Queries) GetUnreadNotificationCount(ctx context.Context, userUsername string) (int64, error) {
	row := q.db.QueryRowContext(ctx, getUnreadNotificationCount, userUsername)
	var unread_count int64
	err := row.Scan(&unread_count)
	return unread_count, err
}

const markAllNotificationsAsRead = `-- name: MarkAllNotificationsAsRead :exec
UPDATE notifications
SET is_read = TRUE
WHERE user_username = $1
  AND is_read = FALSE
`

func (q *Queries) MarkAllNotificationsAsRead(ctx context.Context, userUsername string) error {
	_, err := q.db.ExecContext(ctx, markAllNotificationsAsRead, userUsername)
	return err
}

const markNotificationAsRead = `-- name: MarkNotificationAsRead :one
UPDATE notifications
SET is_read = TRUE
WHERE id = $1
RETURNING id, user_username, type, message_id, is_read, created_at
`

func (q *Queries) MarkNotificationAsRead(ctx context.Context, id int64) (Notification, error) {
	row := q.db.QueryRowContext(ctx, markNotificationAsRead, id)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.UserUsername,
		&i.Type,
		&i.MessageID,
		&i.IsRead,
		&i.CreatedAt,
	)
	return i, err
}
