// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: public_keys.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createPublicKey = `-- name: CreatePublicKey :one
INSERT INTO public_keys (user_id, key)
VALUES ($1, $2)
RETURNING id, user_id, key, created_at, updated_at
`

type CreatePublicKeyParams struct {
	UserID uuid.UUID `json:"user_id"`
	Key    string    `json:"key"`
}

func (q *Queries) CreatePublicKey(ctx context.Context, arg CreatePublicKeyParams) (PublicKey, error) {
	row := q.db.QueryRowContext(ctx, createPublicKey, arg.UserID, arg.Key)
	var i PublicKey
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Key,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAllPublicKeysForUser = `-- name: DeleteAllPublicKeysForUser :exec
DELETE FROM public_keys
WHERE user_id = $1
`

func (q *Queries) DeleteAllPublicKeysForUser(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteAllPublicKeysForUser, userID)
	return err
}

const deletePublicKey = `-- name: DeletePublicKey :exec
DELETE FROM public_keys
WHERE id = $1 AND user_id = $2
`

type DeletePublicKeyParams struct {
	ID     int64     `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) DeletePublicKey(ctx context.Context, arg DeletePublicKeyParams) error {
	_, err := q.db.ExecContext(ctx, deletePublicKey, arg.ID, arg.UserID)
	return err
}

const getPublicKeysByUser = `-- name: GetPublicKeysByUser :many
SELECT id, user_id, key, created_at, updated_at
FROM public_keys
WHERE user_id = $1
ORDER BY created_at ASC
`

func (q *Queries) GetPublicKeysByUser(ctx context.Context, userID uuid.UUID) ([]PublicKey, error) {
	rows, err := q.db.QueryContext(ctx, getPublicKeysByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PublicKey
	for rows.Next() {
		var i PublicKey
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Key,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
