// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sessions.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (
    user_userid,
    type,
    status
) VALUES (
    $1, $2, $3
)
RETURNING id, user_userid, type, status, created_at, updated_at
`

type CreateSessionParams struct {
	UserUserid uuid.UUID     `json:"user_userid"`
	Type       SessionType   `json:"type"`
	Status     SessionStatus `json:"status"`
}

type CreateSessionRow struct {
	ID         uuid.UUID     `json:"id"`
	UserUserid uuid.UUID     `json:"user_userid"`
	Type       SessionType   `json:"type"`
	Status     SessionStatus `json:"status"`
	CreatedAt  time.Time     `json:"created_at"`
	UpdatedAt  time.Time     `json:"updated_at"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (CreateSessionRow, error) {
	row := q.db.QueryRowContext(ctx, createSession, arg.UserUserid, arg.Type, arg.Status)
	var i CreateSessionRow
	err := row.Scan(
		&i.ID,
		&i.UserUserid,
		&i.Type,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions
WHERE id = $1
`

func (q *Queries) DeleteSession(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteSession, id)
	return err
}

const getSession = `-- name: GetSession :one
SELECT id, user_userid, type, status, listen_path, created_at, updated_at
FROM sessions
WHERE user_userid = $1 AND type = $2 LIMIT 1
`

type GetSessionParams struct {
	UserUserid uuid.UUID   `json:"user_userid"`
	Type       SessionType `json:"type"`
}

func (q *Queries) GetSession(ctx context.Context, arg GetSessionParams) (Session, error) {
	row := q.db.QueryRowContext(ctx, getSession, arg.UserUserid, arg.Type)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserUserid,
		&i.Type,
		&i.Status,
		&i.ListenPath,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateSessionStatus = `-- name: UpdateSessionStatus :exec
UPDATE sessions
SET status = $2, updated_at = NOW()
WHERE id = $1
`

type UpdateSessionStatusParams struct {
	ID     uuid.UUID     `json:"id"`
	Status SessionStatus `json:"status"`
}

func (q *Queries) UpdateSessionStatus(ctx context.Context, arg UpdateSessionStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateSessionStatus, arg.ID, arg.Status)
	return err
}
