// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sessions.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createSession = `-- name: CreateSession :exec
INSERT INTO sessions (user_userid, login_id)
VALUES ($1, $2)
`

type CreateSessionParams struct {
	UserUserid uuid.UUID `json:"user_userid"`
	LoginID    uuid.UUID `json:"login_id"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.ExecContext(ctx, createSession, arg.UserUserid, arg.LoginID)
	return err
}

const deleteSessionByLoginID = `-- name: DeleteSessionByLoginID :exec
DELETE FROM sessions
WHERE login_id = $1
`

func (q *Queries) DeleteSessionByLoginID(ctx context.Context, loginID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteSessionByLoginID, loginID)
	return err
}

const getLoginIDsByUserID = `-- name: GetLoginIDsByUserID :many
SELECT login_id
FROM sessions
WHERE user_userid = $1
`

func (q *Queries) GetLoginIDsByUserID(ctx context.Context, userUserid uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.QueryContext(ctx, getLoginIDsByUserID, userUserid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var login_id uuid.UUID
		if err := rows.Scan(&login_id); err != nil {
			return nil, err
		}
		items = append(items, login_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const validateSession = `-- name: ValidateSession :one
SELECT user_userid
FROM sessions
WHERE login_id = $1
`

func (q *Queries) ValidateSession(ctx context.Context, loginID uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, validateSession, loginID)
	var user_userid uuid.UUID
	err := row.Scan(&user_userid)
	return user_userid, err
}
