// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (user_name, hashed_passwd, signup_type)
VALUES ($1, $2, $3)
RETURNING user_id, user_name, hashed_passwd, signup_type, display_name, avatar_url, last_seen_at, created_at, updated_at
`

type CreateUserParams struct {
	UserName     string         `json:"user_name"`
	HashedPasswd sql.NullString `json:"hashed_passwd"`
	SignupType   SignupType     `json:"signup_type"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser, arg.UserName, arg.HashedPasswd, arg.SignupType)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.UserName,
		&i.HashedPasswd,
		&i.SignupType,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.LastSeenAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT user_id, user_name, hashed_passwd, signup_type, display_name, avatar_url, last_seen_at, created_at, updated_at
FROM users
WHERE user_id = $1
LIMIT 1
`

func (q *Queries) GetUserByID(ctx context.Context, userID uuid.UUID) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, userID)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.UserName,
		&i.HashedPasswd,
		&i.SignupType,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.LastSeenAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT user_id, user_name, hashed_passwd, signup_type, display_name, avatar_url, last_seen_at, created_at, updated_at
FROM users
WHERE user_name = $1
LIMIT 1
`

func (q *Queries) GetUserByUsername(ctx context.Context, userName string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByUsername, userName)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.UserName,
		&i.HashedPasswd,
		&i.SignupType,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.LastSeenAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const searchUsers = `-- name: SearchUsers :many
SELECT user_id, user_name, display_name, avatar_url
FROM users
WHERE user_name ILIKE '%' || $1 || '%'
   OR display_name ILIKE '%' || $1 || '%'
ORDER BY user_name
LIMIT 50
`

type SearchUsersRow struct {
	UserID      uuid.UUID      `json:"user_id"`
	UserName    string         `json:"user_name"`
	DisplayName sql.NullString `json:"display_name"`
	AvatarUrl   sql.NullString `json:"avatar_url"`
}

func (q *Queries) SearchUsers(ctx context.Context, dollar_1 sql.NullString) ([]SearchUsersRow, error) {
	rows, err := q.db.QueryContext(ctx, searchUsers, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchUsersRow
	for rows.Next() {
		var i SearchUsersRow
		if err := rows.Scan(
			&i.UserID,
			&i.UserName,
			&i.DisplayName,
			&i.AvatarUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateLastSeen = `-- name: UpdateLastSeen :exec
UPDATE users
SET last_seen_at = NOW()
WHERE user_name = $1
`

func (q *Queries) UpdateLastSeen(ctx context.Context, userName string) error {
	_, err := q.db.ExecContext(ctx, updateLastSeen, userName)
	return err
}

const updateUserProfile = `-- name: UpdateUserProfile :one
UPDATE users
SET display_name = $2,
    avatar_url   = $3,
    updated_at   = NOW()
WHERE user_name = $1
RETURNING user_id, user_name, hashed_passwd, signup_type, display_name, avatar_url, last_seen_at, created_at, updated_at
`

type UpdateUserProfileParams struct {
	UserName    string         `json:"user_name"`
	DisplayName sql.NullString `json:"display_name"`
	AvatarUrl   sql.NullString `json:"avatar_url"`
}

func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUserProfile, arg.UserName, arg.DisplayName, arg.AvatarUrl)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.UserName,
		&i.HashedPasswd,
		&i.SignupType,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.LastSeenAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
