// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user.sql

package db

import (
	"context"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (user_name, hashed_passwd, signup_type)
VALUES ($1, $2, $3)
RETURNING id, user_name, hashed_passwd, signup_type, created_at, updated_at
`

type CreateUserParams struct {
	UserName     string     `json:"user_name"`
	HashedPasswd string     `json:"hashed_passwd"`
	SignupType   SignupType `json:"signup_type"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser, arg.UserName, arg.HashedPasswd, arg.SignupType)
	var i User
	err := row.Scan(
		&i.ID,
		&i.UserName,
		&i.HashedPasswd,
		&i.SignupType,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, user_name, hashed_passwd, signup_type, created_at, updated_at
FROM users
WHERE user_name = $1
LIMIT 1
`

func (q *Queries) GetUserByUsername(ctx context.Context, userName string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByUsername, userName)
	var i User
	err := row.Scan(
		&i.ID,
		&i.UserName,
		&i.HashedPasswd,
		&i.SignupType,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
