apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  annotations:
    run.googleapis.com/ingress: all
    run.googleapis.com/maxScale: '3'
  labels:
    cloud.googleapis.com/location: asia-southeast1
  name: chat-nats
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: '3'
        run.googleapis.com/execution-environment: gen2
        run.googleapis.com/startup-cpu-boost: 'true'
    spec:
      containerConcurrency: 80
      containers:
      - image: zukidocker/chat-nats:latest
        name: chat-nats-1
        ports:
        - containerPort: 8080
          name: http1
        resources:
          limits:
            cpu: 1000m
            memory: 512Mi
        startupProbe:
          failureThreshold: 1
          periodSeconds: 240
          tcpSocket:
            port: 8080
          timeoutSeconds: 240
        volumeMounts:
        - mountPath: /data
          name: gcs-1
      timeoutSeconds: 300
      volumes:
      - csi:
          driver: gcsfuse.run.googleapis.com
          volumeAttributes:
            bucketName: nats_data
        name: gcs-1
  traffic:
  - latestRevision: true
    percent: 100