name: Build and Deploy All

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Version tag'
        required: true
        default: 'latest'

jobs:
  backend:
    uses: ./.github/workflows/build_backend.yml
    with:
      tag: ${{ inputs.tag || 'latest' }}
    secrets: inherit

  gateway:
    uses: ./.github/workflows/build_gateway.yml
    with:
      tag: ${{ inputs.tag || 'latest' }}
    secrets: inherit

  web:
    uses: ./.github/workflows/build_web.yml
    with:
      tag: ${{ inputs.tag || 'latest' }}
    secrets: inherit

